# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: AutoMec ROS CI Workflow w/ ros-industrial/industrial-ci

# This determines when this workflow is run
on: [push, pull_request] # on all pushes and PRs

# # or more fine-grained
# on:
#   # When master or melodic-devel branch is pushed to
#   push:
#     branches: [ dev ]
#   # When there is a pull request against master
#   pull_request:
#     branches: [ dev ]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic, ROS_REPO: testing, BUILDER: catkin_make, TARGET_WORKSPACE='github:AutoMecUA/Automec-AD/', BEFORE_INIT='ros_ci_dependencies.sh'}
          - {ROS_DISTRO: noetic, ROS_REPO: main, BUILDER: catkin_make, TARGET_WORKSPACE='github:AutoMecUA/Automec-AD/', BEFORE_INIT='ros_ci_dependencies.sh'}
    env:
      CCACHE_DIR: /github/home/.ccache # Directory for ccache (and how we enable ccache in industrial_ci)
#       global:
#         - BEFORE_INIT='ros_ci_dependencies.sh'
#         - TARGET_WORKSPACE='github:AutoMecUA/Automec-AD/'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # This step will fetch/store the directory used by ccache before/after the ci run
      - uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}
      # Run industrial_ci
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
